import { Inter } from "next/font/google";
import "@/app/_styles/globals.css";
import Header from "@/app/_components/layouts/Header";
import Container from "@/app/_components/ui/Container";
import Footer from "@/app/_components/layouts/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "Sneakers- %s",
    default: "Welcome In Sneakers",
  },
  description:
    "Generated by Muhammad Abozaid.Sneakers Is A E-Commerce App For Shoes.You Can Order Online and Offline",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col justify-between items-center`}
      >
        <header className="w-[100%] flex-1">
          <Header />
        </header>
        <main className="w-full md:min-h-[calc(100vh-100px)] min-h-screen border flex-1">
          <Container>{children}</Container>
        </main>
        <footer className="w-full flex-1">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
